name: Build OnePlus 13T Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Free up space on runner
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet \
                      /opt/ghc \
                      /usr/local/share/boost \
                      /usr/lib/jvm \
                      /opt/hostedtoolcache \
                      /opt/az \
                      /opt/microsoft \
                      /opt/pipx \
                      /usr/local/lib/android
          sudo apt clean
          echo "After cleanup:"
          df -h

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential curl flex git gnupg \
            libncurses5-dev libssl-dev python-is-python3 rsync unzip xz-utils \
            zip zlib1g-dev ccache

      - name: Set up repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Initialize manifest
        run: |
          mkdir kernel && cd kernel
          repo init --depth=1 -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8750 -m oneplus_13t.xml
          repo sync -j4
          repo forall -c 'git gc --auto'

      - name: Build Kernel with Bazel
        run: |
          cd kernel
          chmod +x kernel_platform/build_with_bazel.py
          export BUILD_CONFIG=kernel_platform/msm-kernel/build.config.oneplus_sm8750
          python3 kernel_platform/build_with_bazel.py --target Image.lz4-dtb --target modules

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: kernel/out/android_kernel_oneplus_sm8750/dist/Image.lz4-dtb

      - name: Upload Kernel Modules
        uses: actions/upload-artifact@v4
        with:
          name: kernel-modules
          path: kernel/out/android_kernel_oneplus_sm8750/dist/modules


