name: Build OnePlus 13T Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Free up space on runner
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet \
                      /opt/ghc \
                      /usr/local/share/boost \
                      /usr/lib/jvm \
                      /opt/hostedtoolcache \
                      /opt/az \
                      /opt/microsoft \
                      /opt/pipx \
                      /usr/local/lib/android
          sudo apt clean
          echo "After cleanup:"
          df -h

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential curl flex git gnupg \
            libncurses5-dev libssl-dev python-is-python3 rsync unzip xz-utils \
            zip zlib1g-dev ccache apt-transport-https
          
      - name: Set up repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Initialize manifest
        run: |
          mkdir kernel && cd kernel
          repo init --depth=1 -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8750 -m oneplus_13t.xml
          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
          repo forall -c 'git gc --auto'

      - name: Build Kernel
        run: |
          cd kernel
          LTO=thin SYSTEM_DLKM_RE_SIGN=1 BUILD_SYSTEM_DLKM=1 ./kernel_platform/oplus/build/oplus_build_kernel.sh sun perf

      - name: Show dist directory structure
        run: |
          tree -L 3 kernel/kernel_platform/out/

      - name: Upload full dist directory
        uses: actions/upload-artifact@v4
        with:
          name: kernel-dist
          path: |
            kernel/kernel_platform/out/msm-kernel-sm8750-perf/dist/

