name: Build OnePlus 13T Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Free up space on runner
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet \
                      /opt/ghc \
                      /usr/local/share/boost \
                      /usr/lib/jvm \
                      /opt/hostedtoolcache \
                      /opt/az \
                      /opt/microsoft \
                      /opt/pipx \
                      /usr/local/lib/android
          sudo apt clean
          echo "After cleanup:"
          df -h

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3 git curl ccache
          
      - name: Set up repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Initialize manifest
        run: |
          mkdir kernel && cd kernel
          repo init --depth=1 -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8750 -m oneplus_13t.xml
          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
          repo forall -c 'git gc --auto'
          # 修复wifi、蓝牙
          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"

      - name: Build Kernel
        run: |
          cd kernel
          LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh sun perf

      - name: Show dist directory structure
        run: |
          tree -L 3 kernel/kernel_platform/out/

      - name: Clone AnyKernel3 and prepare files
        run: |
          git clone https://github.com/Kernel-SU/AnyKernel3.git --depth=1
          rm -rf ./AnyKernel3/.git
          rm -rf ./AnyKernel3/push.sh
          cp kernel/kernel_platform/out/msm-kernel-sun-perf/dist/Image AnyKernel3/Image
          cp kernel/kernel_platform/out/msm-kernel-sun-perf/dist/system_dlkm.erofs.img ./system_dlkm.erofs.img
          cp kernel/kernel_platform/out/msm-kernel-sun-perf/dist/dtbo.img ./dtbo.img

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: Ak3_OnePlus13T_Kernel
          path: ./AnyKernel3/*

      - name: Upload system_dlkm.erofs.img
        uses: actions/upload-artifact@v4
        with:
          name: system_dlkm_erofs_img
          path: system_dlkm.erofs.img

      - name: Upload dtbo.img
        uses: actions/upload-artifact@v4
        with:
          name: dtbo_img
          path: dtbo.img

